#A Workflow is the complete automation process. It is written in a YAML file

name: EC2-pipeline
#An Event is the action that starts the workflow.
on:     
  push:
    branches: main

env:
   AWS_REGION: "ap-south-1"

jobs:       #A Job is a group of related steps. #One workflow can have multiple jobs
 terraform:
   runs-on: ubuntu-latest   #A Runner is the machine that executes your jobs.

   steps:    #A Step is a single task inside a job
    - name: checkout folder
      uses: actions/checkout@v4

    - name: authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ env.AWS_REGION }}

    - name: terraform install
      uses: hashicorp/setup-terraform@v3

    - name: tf.init
      run: terraform init
      

    - name: tf.plan
      run: terraform plan -out=tfplan
      
      
    - name: tf.apply
      run: terraform apply -auto-approve tfplan
      





      
      
